---
# https://github.com/rhobs/prometheus-example-app

namespace: keda-test

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  # optional
  - route.yaml
