---
apiVersion: keda.sh/v1alpha1
kind: KedaController
metadata:
  name: keda
  namespace: openshift-keda
spec:
  metricsServer:
    logLevel: '0'
  operator:
    logLevel: info
    logEncoder: console
  serviceAccount: {}
  watchNamespace: ''